#!/usr/bin/env node
// vim:syntax=javascript

var which = require('which')
var path = require('path')
var commander = require('commander')

commander
	.option('-g, --grep <pattern>', 'Filter using regexp')
	.option('-i, --inbound',        'Log inbound requests only')
	.option('-o, --outbound',       'Log outbound requests only')
	.option('-h, --help',           'Display this help')
	.usage('[our_options] <file_to_trace> [their_options]')

commander.commandHelp = function() {
	return ''
}

commander.parse(process.argv)

commander.on('--help', function(){
	console.log('  Example:');
	console.log('');
	console.log('  This would run "npm install -g yapm" and print out all requests');
	console.log('  that have "registry.npmjs.org" mentioned somewhere:');
	console.log('')
	console.log("  $ expose_curl -g registry.npmjs.org npm install -g yapm");
	console.log('');
})

if (commander.args.length === 0 || commander.H) {
	commander.outputHelp()
	return
}

var argv_0 = process.argv[0]
process.argv = commander.args.slice(0)
process.argv.unshift(argv_0)

var exe = process.argv[1]

if (~exe.indexOf('/')) {
	exe = path.resolve(process.cwd(), exe)
} else {
	exe = which.sync(exe)
}

var ec = require('./')
ec.catch_outgoing_http(function(ee) {
	ec.request_to_curl(ee, console.log)
})
ec.catch_incoming_http(function(ee) {
	ec.request_to_curl(ee, console.log)
})

require(exe)

